# Directories to exclude
exclude-dirs:
  - SOMETHING

# Files to exclude
exclude-files:
  - README.md
  - .gitignore
  - .pre-commit-config.yaml
  - LICENSE

# Add github urls
community-templates:
  - https://github.com/projectdiscovery/nuclei-templates.git
  - https://github.com/0x727/ObserverWard_0x727
  - https://github.com/1in9e/my-nuclei-templates
  - https://github.com/5cr1pt/templates
  - https://github.com/ARPSyndicate/kenzer-templates
  - https://github.com/AshiqurEmon/nuclei_templates.git
  - https://github.com/CharanRayudu/Custom-Nuclei-Templates
  - https://github.com/clarkvoss/Nuclei-Templates
  - https://github.com/d3sca/Nuclei_Templates
  - https://github.com/daffainfo/my-nuclei-templates
  - https://github.com/esetal/nuclei-bb-templates
  - https://github.com/ethicalhackingplayground/erebus-templates
  - https://github.com/geeknik/nuclei-templates-1
  - https://github.com/geeknik/the-nuclei-templates
  - https://github.com/Harish4948/Nuclei-Templates
  - https://github.com/im403/nuclei-temp
  - https://github.com/javaongsan/nuclei-templates
  - https://github.com/kabilan1290/templates
  - https://github.com/medbsq/ncl
  - https://github.com/meme-lord/Custom-Nuclei-Templates
  - https://github.com/MR-pentestGuy/nuclei-templates
  - https://github.com/n1f2c3/mytemplates
  - https://github.com/NitinYadav00/My-Nuclei-Templates
  - https://github.com/notnotnotveg/nuclei-custom-templates
  - https://github.com/obreinx/nuceli-templates
  - https://github.com/optiv/mobile-nuclei-templates
  - https://github.com/panch0r3d/nuclei-templates
  - https://github.com/peanuth8r/Nuclei_Templates
  - https://github.com/pikpikcu/my-nuclei-templates
  - https://github.com/pikpikcu/nuclei-templates
  - https://github.com/R-s0n/Custom_Vuln_Scan_Templates
  - https://github.com/rafaelcaria/Nuclei-Templates
  - https://github.com/rahulkadavil/nuclei-templates
  - https://github.com/randomstr1ng/nuclei-sap-templates
  - https://github.com/redteambrasil/nuclei-templates
  - https://github.com/ree4pwn/my-nuclei-templates
  - https://github.com/sadnansakin/my-nuclei-templates
  - https://github.com/Saimonkabir/Nuclei-Templates
  - https://github.com/Saptak9983/Nuclei-Template
  - https://github.com/securitytest3r/nuclei_templates_work
  - https://github.com/sharathkramadas/k8s-nuclei-templates
  - https://github.com/shifa123/detections
  - https://github.com/smaranchand/nuclei-templates
  - https://github.com/Str1am/my-nuclei-templates
  - https://github.com/System00-Security/backflow
  - https://github.com/test502git/log4j-fuzz-head-poc
  - https://github.com/thebrnwal/Content-Injection-Nuclei-Script
  - https://github.com/thelabda/nuclei-templates
  - https://github.com/yavolo/nuclei-templates
  - https://github.com/z3bd/nuclei-templates
  - https://github.com/zinminphyo0/KozinTemplates
  - https://github.com/c-sh0/nuclei_templates
  - https://github.com/Akokonunes/Private-Nuclei-Templates
