# Directories to exclude
exclude-dirs:
  - SOMETHING

# Files to exclude
exclude-files:
  - README.md
  - .gitignore
  - .pre-commit-config.yaml
  - LICENSE

# Add github urls
community-templates:
  - https://github.com/projectdiscovery/nuclei-templates.git
  - https://github.com/geeknik/the-nuclei-templates
  - https://github.com/pikpikcu/my-nuclei-templates
  - https://github.com/panch0r3d/nuclei-templates
  - https://github.com/ARPSyndicate/kenzer-templates
  - https://github.com/medbsq/ncl
  - https://github.com/foulenzer/foulenzer-templates
  - https://github.com/im403/nuclei-temp
  - https://github.com/System00-Security/backflow
  - https://github.com/geeknik/nuclei-templates-1
  - https://github.com/esetal/nuclei-bb-templates
  - https://github.com/notnotnotveg/nuclei-custom-templates
  - https://github.com/clarkvoss/Nuclei-Templates
  - https://github.com/z3bd/nuclei-templates
  - https://github.com/joanbono/nuclei-templates
  - https://github.com/peanuth8r/Nuclei_Templates
  - https://github.com/thebrnwal/Content-Injection-Nuclei-Script
  - https://github.com/ree4pwn/my-nuclei-templates
  - https://github.com/optiv/mobile-nuclei-templates
  - https://github.com/obreinx/nuceli-templates
  - https://github.com/randomstr1ng/nuclei-sap-templates
  - https://github.com/CharanRayudu/Custom-Nuclei-Templates
  - https://github.com/zinminphyo0/KozinTemplates
  - https://github.com/n1f2c3/mytemplates
  - https://github.com/kabilan1290/templates
  - https://github.com/smaranchand/nuclei-templates
  - https://github.com/Saimonkabir/Nuclei-Templates
  - https://github.com/yavolo/nuclei-templates
  - https://github.com/sadnansakin/my-nuclei-templates
  - https://github.com/5cr1pt/templates
  - https://github.com/rahulkadavil/nuclei-templates
  - https://github.com/shifa123/detections
  - https://github.com/daffainfo/my-nuclei-templates
